# Generated by Django 3.2 on 2023-08-09 11:59

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE SCHEMA IF NOT EXISTS content;
            """,
            reverse_sql='DROP SCHEMA content CASCADE;',
        ),
        migrations.CreateModel(
            name='Filmwork',
            fields=[
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    models.DateTimeField(auto_now=True, verbose_name='updated'),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('title', models.TextField(verbose_name='title')),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='description'),
                ),
                (
                    'rating',
                    models.FloatField(
                        blank=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name='rating',
                    ),
                ),
                (
                    'type',
                    models.TextField(
                        choices=[('movie', 'Movie'), ('tw_show', 'Tv Show')],
                        default='movie',
                        verbose_name='type',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Кинопроизведение',
                'verbose_name_plural': 'Кинопроизведения',
                'db_table': 'content"."film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    models.DateTimeField(auto_now=True, verbose_name='updated'),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='description'),
                ),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'content"."genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    models.DateTimeField(auto_now=True, verbose_name='updated'),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('full_name', models.TextField(verbose_name='full_name')),
            ],
            options={
                'verbose_name': 'Актёр',
                'verbose_name_plural': 'Актёры',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='PersonFilmwork',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'film_work',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='movies.filmwork',
                    ),
                ),
                (
                    'person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='movies.person',
                    ),
                ),
            ],
            options={'db_table': 'content"."person_film_work',},
        ),
        migrations.CreateModel(
            name='GenreFilmwork',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'film_work',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='movies.filmwork',
                    ),
                ),
                (
                    'genre',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='movies.genre',
                    ),
                ),
            ],
            options={'db_table': 'content"."genre_film_work',},
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(
                through='movies.GenreFilmwork', to='movies.Genre'
            ),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(
                through='movies.PersonFilmwork', to='movies.Person'
            ),
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(
                fields=('film_work', 'genre'), name='unique_film_work_genre'
            ),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(
                fields=['rating'], name='film_work_rating_30c254_idx'
            ),
        ),
    ]
