# Generated by Django 3.2 on 2023-08-09 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20230809_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='rating',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name='rating',
            ),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.TextField(
                choices=[('movie', 'Movie'), ('tw_show', 'Tv Show')],
                default='movie',
                null=True,
                verbose_name='type',
            ),
        ),
    ]
