# Generated by Django 3.2 on 2023-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230809_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='description',
            field=models.TextField(
                blank=True, null=True, verbose_name='description'
            ),
        ),
    ]
