# Generated by Django 3.2 on 2023-08-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20230810_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(
                blank=True,
                choices=[
                    ('actor', 'Actor'),
                    ('tw_show', 'Director'),
                    ('writer', 'Writer'),
                ],
                default='actor',
                verbose_name='role',
            ),
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(
                fields=('film_work', 'person', 'role'),
                name='unique_film_work_pseron_role',
            ),
        ),
    ]
