# Generated by Django 3.2 on 2023-08-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20230813_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='creation_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
