# Generated by Django 3.2 on 2023-09-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_filmwork_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.TextField(
                choices=[('movie', 'Movie'), ('tv_show', 'Tv Show')],
                default='movie',
                verbose_name='type',
            ),
        ),
    ]
