version: '3'

services:
  serv:
    build: config
    volumes:
      - static_volume:/opt/config/static
      - media_volume:/opt/config/media
    env_file:
      - ./.env
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - /dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/opt/config/static
      - media_volume:/opt/config/media
    depends_on:
      - serv
    ports:
      - "8000:80"
  
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  cron:
    build: cron
    env_file:
      - ./.env
    depends_on:
      - db
      - elastic
#наставники сказали что индекс можно создавать через curl)

volumes:
  pg_data:
  static_volume:
  media_volume:
